apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: ml-infer-deployment
  ports:
  - name: default
    port: 5000
    targetPort: 5000
