apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: ml-infer # Apply to deployment labeled ml-infer
  ports:
  - name: default
    port: 5000
    targetPort: 5000
    nodePort: 31111
