FROM nvcr.io/nvidia/tensorrt:23.10-py3 

LABEL description="This image uses ubuntu 22.04 with Python 3.10 and \
    the others dependencies are TensorRT 8.6.3 CUDA 12.2.2 cuDNN 8.9.5 \
    cuBLAS 12.2.5 NCCL 2.19.3"
LABEL maintainer="Tinnapop Duangtha, tinnapopduangtha@gmail.com"

# Update
RUN apt-get update

# Cleanup
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements.txt
COPY docker/requirements.txt .

# PIP dependencies
RUN python3 -m pip install --default-timeout=100 \
    --no-cache-dir -r requirements.txt

# Expose a port for incoming requests
EXPOSE 5000

# Workinf directory
RUN mkdir -p /ml-inference
WORKDIR "/ml-inference"