FROM nvcr.io/nvidia/tensorrt:23.10-py3 

LABEL description="This image uses ubuntu 22.04 with Python 3.10 and \
    the others dependencies are TensorRT 8.6.3 CUDA 12.2.2 cuDNN 8.9.5 \
    cuBLAS 12.2.5 NCCL 2.19.3"
LABEL maintainer="Tinnapop Duangtha, tinnapopduangtha@gmail.com"

# Update
RUN apt-get update

# Cleanup
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# PIP dependencies
RUN python3 -m pip install --default-timeout=100 \
    cuda-python \
    opencv-python-headless

# Copyfiles
RUN mkdir -p /inference
COPY ../src/inference/ /inference

# Workinf directory
WORKDIR "/inference"

# Specifies the default command to run when the container starts.
# CMD ["python3", "usecases/morning_talk.py"]